template = "https://github.com/giellalt/template-lang-und"
rev_id = 253
template_sha = "5e69b0634aa0bd9773dece52e5b15d3003d605f1"

[replacements]
__GLOTTOLOG_ID__ = "oldn1244"
__REPO__ = "lang-non"
__UND2C__ = "non"
__UNDEFINED__ = "Old Norse"
__UND__ = "non"
